# Netlify configuration file

[build]
  # Command to build the site
  command = "yarn build"
  
  # Directory to publish (relative to the root of the repository)
  publish = "build"

[build.environment]
NODE_VERSION = "20.19.0"
